wandb_version: 1

system:
  desc: null
  value:
    seed: 3407
    work_dir: out/shakespeare-test-vision-gpu-3
data:
  desc: null
  value:
    n_tokens: 32
data_filepath:
  desc: null
  value: data/shakespeare_char/input.txt
model:
  desc: null
  value:
    n_tokens: 32
    n_layer: 6
    n_head: 6
    n_embd: 96
    dropout: 0.1
    bias: false
    is_transposed: true
    is_causal: false
    vocab_size: 65
trainer:
  desc: null
  value:
    device: auto
    num_workers: 4
    max_iters: 1001
    batch_size: 2048
    learning_rate: 0.0003
    betas:
    - 0.9
    - 0.95
    weight_decay: 0.1
    grad_norm_clip: 1.0
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711985320.776575
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
